<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TestNG" duration-ms="4239" started-at="2016-06-15T22:49:31Z" finished-at="2016-06-15T22:49:35Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.wissenteil.oftest.test.RunCucumberTests@13deb50e]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="RunCukes" duration-ms="4239" started-at="2016-06-15T22:49:31Z" finished-at="2016-06-15T22:49:35Z">
      <class name="com.wissenteil.oftest.test.RunCucumberTests">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.wissenteil.oftest.test.RunCucumberTests@13deb50e]" name="setUpClass" is-config="true" duration-ms="223" started-at="2016-06-16T00:49:31Z" finished-at="2016-06-16T00:49:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.wissenteil.oftest.test.RunCucumberTests@13deb50e]" name="setup" is-config="true" duration-ms="1993" started-at="2016-06-16T00:49:31Z" finished-at="2016-06-16T00:49:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.wissenteil.oftest.test.RunCucumberTests@13deb50e]" name="feature" duration-ms="1920" started-at="2016-06-16T00:49:33Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2016-06-16T00:49:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test Signup process]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected:<https://wiesenttal.herokuapp.com/signup> but was:<https://wiesenttal.herokuapp.com/>]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected:<https://wiesenttal.herokuapp.com/signup> but was:<https://wiesenttal.herokuapp.com/>
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.AssertionError: expected:<https://wiesenttal.herokuapp.com/signup> but was:<https://wiesenttal.herokuapp.com/>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.wissenteil.oftest.stepDefinition.TestSteps.isSignupPageLoaded(TestSteps.java:35)
	at âœ½.Then I will see the sign up page(TestSignupProcess.feature:7)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.wissenteil.oftest.test.RunCucumberTests@13deb50e]" name="tearDown" is-config="true" duration-ms="10" started-at="2016-06-16T00:49:35Z" finished-at="2016-06-16T00:49:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.wissenteil.oftest.test.RunCucumberTests@13deb50e]" name="tearDownClass" is-config="true" duration-ms="9" started-at="2016-06-16T00:49:35Z" finished-at="2016-06-16T00:49:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.wissenteil.oftest.test.RunCucumberTests -->
    </test> <!-- RunCukes -->
  </suite> <!-- TestNG -->
</testng-results>
